# Generated by Django 5.0.6 on 2024-07-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=150)),
                ('card_description', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('images', models.ImageField(upload_to='popular_image')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('popular', 'popular')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('cruise trip', 'Cruise trips'), ('beach vacation', 'Beach Vacations'), ('cultural trip', 'Cultural Trips'), ('adventure trip', 'Adventure Trips'), ('family trip', 'Family Trips')], max_length=100),
        ),
    ]
